targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
      gql_typed|gql_typed_generator:
        enabled: true
        options:
          schema: example|lib/schema.graphql
          scalers:
            - gql_name: DateTime
              dart_name: DateTime
              parser_import: "package:example/gql_scalers.dart"
